// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package zedboard_regs_pkg;

    localparam ZEDBOARD_REGS_DATA_WIDTH = 8;
    localparam ZEDBOARD_REGS_MIN_ADDR_WIDTH = 16;
    localparam ZEDBOARD_REGS_SIZE = 'h100e;

    typedef struct {
        logic [7:0] next;
    } zedboard_regs__build_id_byte__data__in_t;

    typedef struct {
        zedboard_regs__build_id_byte__data__in_t data;
    } zedboard_regs__build_id_byte__in_t;

    typedef struct {
        logic next;
    } zedboard_regs__diag__PHY_STATUS__present__in_t;

    typedef struct {
        logic next;
    } zedboard_regs__diag__PHY_STATUS__init_done__in_t;

    typedef struct {
        logic next;
    } zedboard_regs__diag__PHY_STATUS__irq__in_t;

    typedef struct {
        zedboard_regs__diag__PHY_STATUS__present__in_t present;
        zedboard_regs__diag__PHY_STATUS__init_done__in_t init_done;
        zedboard_regs__diag__PHY_STATUS__irq__in_t irq;
    } zedboard_regs__diag__PHY_STATUS__in_t;

    typedef struct {
        logic [4:0] next;
    } zedboard_regs__diag__PHY_ADDR__addr__in_t;

    typedef struct {
        zedboard_regs__diag__PHY_ADDR__addr__in_t addr;
    } zedboard_regs__diag__PHY_ADDR__in_t;

    typedef struct {
        logic next;
    } zedboard_regs__diag__MDIO_CTRL__busy__in_t;

    typedef struct {
        zedboard_regs__diag__MDIO_CTRL__busy__in_t busy;
    } zedboard_regs__diag__MDIO_CTRL__in_t;

    typedef struct {
        logic [7:0] next;
    } zedboard_regs__mdio_rdata_byte__data__in_t;

    typedef struct {
        zedboard_regs__mdio_rdata_byte__data__in_t data;
    } zedboard_regs__mdio_rdata_byte__in_t;

    typedef struct {
        zedboard_regs__build_id_byte__in_t BUILD_ID_0;
        zedboard_regs__build_id_byte__in_t BUILD_ID_1;
        zedboard_regs__build_id_byte__in_t BUILD_ID_2;
        zedboard_regs__build_id_byte__in_t BUILD_ID_3;
        zedboard_regs__diag__PHY_STATUS__in_t PHY_STATUS;
        zedboard_regs__diag__PHY_ADDR__in_t PHY_ADDR;
        zedboard_regs__diag__MDIO_CTRL__in_t MDIO_CTRL;
        zedboard_regs__mdio_rdata_byte__in_t MDIO_RDATA_0;
        zedboard_regs__mdio_rdata_byte__in_t MDIO_RDATA_1;
    } zedboard_regs__diag__in_t;

    typedef struct {
        zedboard_regs__diag__in_t diag;
    } zedboard_regs__in_t;

    typedef struct {
        logic [4:0] value;
    } zedboard_regs__diag__MDIO_REG__reg_addr__out_t;

    typedef struct {
        zedboard_regs__diag__MDIO_REG__reg_addr__out_t reg_addr;
    } zedboard_regs__diag__MDIO_REG__out_t;

    typedef struct {
        logic [7:0] value;
    } zedboard_regs__diag__MDIO_WDATA_0__data__out_t;

    typedef struct {
        zedboard_regs__diag__MDIO_WDATA_0__data__out_t data;
    } zedboard_regs__diag__MDIO_WDATA_0__out_t;

    typedef struct {
        logic [7:0] value;
    } zedboard_regs__diag__MDIO_WDATA_1__data__out_t;

    typedef struct {
        zedboard_regs__diag__MDIO_WDATA_1__data__out_t data;
    } zedboard_regs__diag__MDIO_WDATA_1__out_t;

    typedef struct {
        logic value;
    } zedboard_regs__diag__MDIO_CTRL__go__out_t;

    typedef struct {
        logic value;
    } zedboard_regs__diag__MDIO_CTRL__write__out_t;

    typedef struct {
        zedboard_regs__diag__MDIO_CTRL__go__out_t go;
        zedboard_regs__diag__MDIO_CTRL__write__out_t write;
    } zedboard_regs__diag__MDIO_CTRL__out_t;

    typedef struct {
        logic [4:0] value;
        logic swmod;
    } zedboard_regs__diag__IDELAY_TAP__tap__out_t;

    typedef struct {
        zedboard_regs__diag__IDELAY_TAP__tap__out_t tap;
    } zedboard_regs__diag__IDELAY_TAP__out_t;

    typedef struct {
        zedboard_regs__diag__MDIO_REG__out_t MDIO_REG;
        zedboard_regs__diag__MDIO_WDATA_0__out_t MDIO_WDATA_0;
        zedboard_regs__diag__MDIO_WDATA_1__out_t MDIO_WDATA_1;
        zedboard_regs__diag__MDIO_CTRL__out_t MDIO_CTRL;
        zedboard_regs__diag__IDELAY_TAP__out_t IDELAY_TAP;
    } zedboard_regs__diag__out_t;

    typedef struct {
        zedboard_regs__diag__out_t diag;
    } zedboard_regs__out_t;
endpackage
