// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module zedboard_regs (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [15:0] s_apb_paddr,
        input wire [7:0] s_apb_pwdata,
        input wire [0:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [7:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input zedboard_regs_pkg::zedboard_regs__in_t hwif_in,
        output zedboard_regs_pkg::zedboard_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [15:0] cpuif_addr;
    logic [7:0] cpuif_wr_data;
    logic [7:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [7:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= s_apb_paddr[15:0];
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<1; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic SCRATCH;
            logic BUILD_ID_0;
            logic BUILD_ID_1;
            logic BUILD_ID_2;
            logic BUILD_ID_3;
            logic PHY_STATUS;
            logic PHY_ADDR;
            logic MDIO_REG;
            logic MDIO_WDATA_0;
            logic MDIO_WDATA_1;
            logic MDIO_CTRL;
            logic MDIO_RDATA_0;
            logic MDIO_RDATA_1;
            logic IDELAY_TAP;
        } diag;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [15:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [7:0] decoded_wr_data;
    logic [7:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.diag.SCRATCH = cpuif_req_masked & (cpuif_addr == 16'h1000);
        decoded_reg_strb.diag.BUILD_ID_0 = cpuif_req_masked & (cpuif_addr == 16'h1001) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.BUILD_ID_1 = cpuif_req_masked & (cpuif_addr == 16'h1002) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.BUILD_ID_2 = cpuif_req_masked & (cpuif_addr == 16'h1003) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.BUILD_ID_3 = cpuif_req_masked & (cpuif_addr == 16'h1004) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.PHY_STATUS = cpuif_req_masked & (cpuif_addr == 16'h1005) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.PHY_ADDR = cpuif_req_masked & (cpuif_addr == 16'h1006) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.MDIO_REG = cpuif_req_masked & (cpuif_addr == 16'h1007);
        decoded_reg_strb.diag.MDIO_WDATA_0 = cpuif_req_masked & (cpuif_addr == 16'h1008);
        decoded_reg_strb.diag.MDIO_WDATA_1 = cpuif_req_masked & (cpuif_addr == 16'h1009);
        decoded_reg_strb.diag.MDIO_CTRL = cpuif_req_masked & (cpuif_addr == 16'h100a);
        decoded_reg_strb.diag.MDIO_RDATA_0 = cpuif_req_masked & (cpuif_addr == 16'h100b) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.MDIO_RDATA_1 = cpuif_req_masked & (cpuif_addr == 16'h100c) & !cpuif_req_is_wr;
        decoded_reg_strb.diag.IDELAY_TAP = cpuif_req_masked & (cpuif_addr == 16'h100d);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [7:0] next;
                    logic load_next;
                } data;
            } SCRATCH;
            struct {
                struct {
                    logic [4:0] next;
                    logic load_next;
                } reg_addr;
            } MDIO_REG;
            struct {
                struct {
                    logic [7:0] next;
                    logic load_next;
                } data;
            } MDIO_WDATA_0;
            struct {
                struct {
                    logic [7:0] next;
                    logic load_next;
                } data;
            } MDIO_WDATA_1;
            struct {
                struct {
                    logic next;
                    logic load_next;
                } go;
                struct {
                    logic next;
                    logic load_next;
                } write;
            } MDIO_CTRL;
            struct {
                struct {
                    logic [4:0] next;
                    logic load_next;
                } tap;
            } IDELAY_TAP;
        } diag;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [7:0] value;
                } data;
            } SCRATCH;
            struct {
                struct {
                    logic [4:0] value;
                } reg_addr;
            } MDIO_REG;
            struct {
                struct {
                    logic [7:0] value;
                } data;
            } MDIO_WDATA_0;
            struct {
                struct {
                    logic [7:0] value;
                } data;
            } MDIO_WDATA_1;
            struct {
                struct {
                    logic value;
                } go;
                struct {
                    logic value;
                } write;
            } MDIO_CTRL;
            struct {
                struct {
                    logic [4:0] value;
                } tap;
            } IDELAY_TAP;
        } diag;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: zedboard_regs.diag.SCRATCH.data
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.SCRATCH.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.SCRATCH && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.SCRATCH.data.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.diag.SCRATCH.data.next = next_c;
        field_combo.diag.SCRATCH.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.SCRATCH.data.value <= 8'h0;
        end else begin
            if(field_combo.diag.SCRATCH.data.load_next) begin
                field_storage.diag.SCRATCH.data.value <= field_combo.diag.SCRATCH.data.next;
            end
        end
    end
    // Field: zedboard_regs.diag.MDIO_REG.reg_addr
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.MDIO_REG.reg_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.MDIO_REG && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.MDIO_REG.reg_addr.value & ~decoded_wr_biten[4:0]) | (decoded_wr_data[4:0] & decoded_wr_biten[4:0]);
            load_next_c = '1;
        end
        field_combo.diag.MDIO_REG.reg_addr.next = next_c;
        field_combo.diag.MDIO_REG.reg_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.MDIO_REG.reg_addr.value <= 5'h0;
        end else begin
            if(field_combo.diag.MDIO_REG.reg_addr.load_next) begin
                field_storage.diag.MDIO_REG.reg_addr.value <= field_combo.diag.MDIO_REG.reg_addr.next;
            end
        end
    end
    assign hwif_out.diag.MDIO_REG.reg_addr.value = field_storage.diag.MDIO_REG.reg_addr.value;
    // Field: zedboard_regs.diag.MDIO_WDATA_0.data
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.MDIO_WDATA_0.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.MDIO_WDATA_0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.MDIO_WDATA_0.data.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.diag.MDIO_WDATA_0.data.next = next_c;
        field_combo.diag.MDIO_WDATA_0.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.MDIO_WDATA_0.data.value <= 8'h0;
        end else begin
            if(field_combo.diag.MDIO_WDATA_0.data.load_next) begin
                field_storage.diag.MDIO_WDATA_0.data.value <= field_combo.diag.MDIO_WDATA_0.data.next;
            end
        end
    end
    assign hwif_out.diag.MDIO_WDATA_0.data.value = field_storage.diag.MDIO_WDATA_0.data.value;
    // Field: zedboard_regs.diag.MDIO_WDATA_1.data
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.MDIO_WDATA_1.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.MDIO_WDATA_1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.MDIO_WDATA_1.data.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.diag.MDIO_WDATA_1.data.next = next_c;
        field_combo.diag.MDIO_WDATA_1.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.MDIO_WDATA_1.data.value <= 8'h0;
        end else begin
            if(field_combo.diag.MDIO_WDATA_1.data.load_next) begin
                field_storage.diag.MDIO_WDATA_1.data.value <= field_combo.diag.MDIO_WDATA_1.data.next;
            end
        end
    end
    assign hwif_out.diag.MDIO_WDATA_1.data.value = field_storage.diag.MDIO_WDATA_1.data.value;
    // Field: zedboard_regs.diag.MDIO_CTRL.go
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.MDIO_CTRL.go.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.MDIO_CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.MDIO_CTRL.go.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.diag.MDIO_CTRL.go.next = next_c;
        field_combo.diag.MDIO_CTRL.go.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.MDIO_CTRL.go.value <= 1'h0;
        end else begin
            if(field_combo.diag.MDIO_CTRL.go.load_next) begin
                field_storage.diag.MDIO_CTRL.go.value <= field_combo.diag.MDIO_CTRL.go.next;
            end
        end
    end
    assign hwif_out.diag.MDIO_CTRL.go.value = field_storage.diag.MDIO_CTRL.go.value;
    // Field: zedboard_regs.diag.MDIO_CTRL.write
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.MDIO_CTRL.write.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.MDIO_CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.MDIO_CTRL.write.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.diag.MDIO_CTRL.write.next = next_c;
        field_combo.diag.MDIO_CTRL.write.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.MDIO_CTRL.write.value <= 1'h0;
        end else begin
            if(field_combo.diag.MDIO_CTRL.write.load_next) begin
                field_storage.diag.MDIO_CTRL.write.value <= field_combo.diag.MDIO_CTRL.write.next;
            end
        end
    end
    assign hwif_out.diag.MDIO_CTRL.write.value = field_storage.diag.MDIO_CTRL.write.value;
    // Field: zedboard_regs.diag.IDELAY_TAP.tap
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.diag.IDELAY_TAP.tap.value;
        load_next_c = '0;
        if(decoded_reg_strb.diag.IDELAY_TAP && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.diag.IDELAY_TAP.tap.value & ~decoded_wr_biten[4:0]) | (decoded_wr_data[4:0] & decoded_wr_biten[4:0]);
            load_next_c = '1;
        end
        field_combo.diag.IDELAY_TAP.tap.next = next_c;
        field_combo.diag.IDELAY_TAP.tap.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.diag.IDELAY_TAP.tap.value <= 5'hc;
        end else begin
            if(field_combo.diag.IDELAY_TAP.tap.load_next) begin
                field_storage.diag.IDELAY_TAP.tap.value <= field_combo.diag.IDELAY_TAP.tap.next;
            end
        end
    end
    assign hwif_out.diag.IDELAY_TAP.tap.value = field_storage.diag.IDELAY_TAP.tap.value;
    assign hwif_out.diag.IDELAY_TAP.tap.swmod = decoded_reg_strb.diag.IDELAY_TAP && decoded_req_is_wr && |(decoded_wr_biten[4:0]);

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [15:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [7:0] readback_data;
    always_comb begin
        automatic logic [7:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 16'h1000) begin
            readback_data_var[7:0] = field_storage.diag.SCRATCH.data.value;
        end
        if(rd_mux_addr == 16'h1001) begin
            readback_data_var[7:0] = hwif_in.diag.BUILD_ID_0.data.next;
        end
        if(rd_mux_addr == 16'h1002) begin
            readback_data_var[7:0] = hwif_in.diag.BUILD_ID_1.data.next;
        end
        if(rd_mux_addr == 16'h1003) begin
            readback_data_var[7:0] = hwif_in.diag.BUILD_ID_2.data.next;
        end
        if(rd_mux_addr == 16'h1004) begin
            readback_data_var[7:0] = hwif_in.diag.BUILD_ID_3.data.next;
        end
        if(rd_mux_addr == 16'h1005) begin
            readback_data_var[0] = hwif_in.diag.PHY_STATUS.present.next;
            readback_data_var[1] = hwif_in.diag.PHY_STATUS.init_done.next;
            readback_data_var[2] = hwif_in.diag.PHY_STATUS.irq.next;
        end
        if(rd_mux_addr == 16'h1006) begin
            readback_data_var[4:0] = hwif_in.diag.PHY_ADDR.addr.next;
        end
        if(rd_mux_addr == 16'h1007) begin
            readback_data_var[4:0] = field_storage.diag.MDIO_REG.reg_addr.value;
        end
        if(rd_mux_addr == 16'h1008) begin
            readback_data_var[7:0] = field_storage.diag.MDIO_WDATA_0.data.value;
        end
        if(rd_mux_addr == 16'h1009) begin
            readback_data_var[7:0] = field_storage.diag.MDIO_WDATA_1.data.value;
        end
        if(rd_mux_addr == 16'h100a) begin
            readback_data_var[0] = field_storage.diag.MDIO_CTRL.go.value;
            readback_data_var[1] = field_storage.diag.MDIO_CTRL.write.value;
            readback_data_var[7] = hwif_in.diag.MDIO_CTRL.busy.next;
        end
        if(rd_mux_addr == 16'h100b) begin
            readback_data_var[7:0] = hwif_in.diag.MDIO_RDATA_0.data.next;
        end
        if(rd_mux_addr == 16'h100c) begin
            readback_data_var[7:0] = hwif_in.diag.MDIO_RDATA_1.data.next;
        end
        if(rd_mux_addr == 16'h100d) begin
            readback_data_var[4:0] = field_storage.diag.IDELAY_TAP.tap.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
